<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Lazarus.Backend</RootNamespace>
    <AssemblyName>Lazarus.Backend</AssemblyName>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\App.Shared\App.Shared.csproj" />
  </ItemGroup>

</Project>

